### PR TITLE
Update libusb driver to current API

### PR DESCRIPTION
**Pull request by ngwese**
- Use pkg-config to find libusb
- Optionally allow libusb builds on macOS

This PR theoretically returns the `libusb-1.0` based driver back to health. The code compiles and the `helloSoundplane` example produces plausible ascii art on the tested platforms.

The somewhat unusual `external/libusb` directory and the embedded `findlibusb.cmake` macro were removed in favor of using the built in cmake support for locating libraries via `pkg-config`. Modifications to the `SP_USE_LIBUSB` logic retain the default behavior of using the native IOKit drivers on APPLE platforms but allow `libusb` to be used on APPLE platforms by explicitly defining the variable, i.e. `cmake -DSP_USE_LIBUSB=ON ..`

Tested on:
| OS | Arch | Driver | Compiler |
| --- | ----- | ----- | ----------|
| macOS Mojave (10.14) | x86_64 | IOKit | clang 11.0.0 |
| macOS Mojave (10.14) | x84_64 | libusb-1.0 (installed via homebrew) | clang 11.0.0 |
| Debian Buster | x86_64 | libusb-1.0 | gcc 8.3.0 |
| Raspbian ~Stretch | rpi3+/rpi4 armhf | libusb-1.0 | gcc 6.3.0 |

### CODE REVIEW

**Comment by ngwese** [comment]
Included an additional commit which restores `.deb` (Debian package) generation.

**Comment by randyjonesworld** [comment]
This is huge! I have other tasks this week but will make time to look this over and merge it soon. Thanks again for your contribution.

**Comment by ngwese** [comment]
Just checking in on this one. If there is anything controversial about the changes don’t hesitate to call it out and I can address as needed.

**Comment by randyjonesworld** [comment]
Hi Greg,

Absolutely nothing controversial and I do appreciate your contribution.  It’s just that I have bugs I’m working on that are affecting more people and I’m prioritizing that work.  Sorry for the delay.

–Randy

**Comment by ngwese** [comment]
Bumping the visibly of this as it came up in conversation around the feasibility of soundplane + norns

**Comment by randyjonesworld** [comment]
Heard. Will take a look soon.

**Comment by randyjonesworld** [comment]
OK, I've tested both the IOKit and libusb versions on MacOS, and both are working here as well. Excited to see where this can take things. Thanks again.

**Pull request merged**
